Add `SpokeRegistered` event
thehubbleproject/hubble-contracts pull request #676
Opened 2021-12-20 09:51 UTC by max-sidorov

Added an event that emits after the registration of spokes.

2021-12-21 15:10 UTC, msieczko requested changes
I'd rename `RegisteredSpoke` -> `SpokeRegistered`. Better grammar and more consistent with other events.

2021-12-22 11:17 UTC, msieczko commented
This PR would make syncing registered spokes much easier. @jacque006 could you take a look?

2021-12-23 02:06 UTC, jacque006 approved these changes

2021-12-23 02:06 UTC, jacque006 commented on contracts/SpokeRegistry.sol
>      }
Would be nice to have a fast test case for this function and the new event, but given that there is not an existing case will leave at author's discretion.

2021-12-29 11:41 UTC, msieczko approved these changes

2021-12-30 01:39 UTC, jacque006 approved these changes

2021-12-30 01:39 UTC, merged